version: '3'
services:
  date-api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - rabbitmq
      - cache
    volumes:
      - .:/app
      - /app/node_modules
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    logging:
      driver: none
  mongodb:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongodata:/data/db
    logging:
      driver: none
volumes:
  mongodata:
    driver: local
  cache:
    driver: local
